import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Achraf Hannoun | Web Developer",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang={locale}>
      <body className={inter.className + " bg-[#FAF1E4]"}>
        <NavBar lang={locale} />
        {children}
      </body>
    </html>
  );
}
